modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="swoobies"
version="1.0.0"
displayName="Swoobies"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Swerik, MCreator"

[[dependencies.swoobies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



